apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-scale
  name: node-scale
spec:
  ports:
    - name: node-scale
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: node-scale
  type: NodePort
status:
  loadBalancer: {}